
import { BaseMessage } from "@langchain/core/messages";

/**
 * Represents the state for a Plan-and-Execute workflow.
 * @interface
 */
export type PlanExecuteState = {
  /**
   * The original input query.
   * @type {string}
   */
  input: string;
  /**
   * The multi-step plan generated by the planner.
   * @type {string[]}
   */
  plan: string[];
  /**
   * A list of previously executed steps and their results.
   * @type {[string, string][]}
   */
  pastSteps: [string, string][];
  /**
   * The final response generated by the agent.
   * @type {string}
   */
  response: string;
  /**
   * Messages exchanged during the workflow.
   * @type {BaseMessage[]}
   */
  messages: BaseMessage[];
  /**
   * The next node to execute in the workflow.
   * @type {string}
   */
  next: string;
};
