
import { BaseMessage } from "@langchain/core/messages";

/**
 * Represents the state for a Reflection workflow.
 * @interface
 */
export type ReflectionState = {
  /**
   * The user's initial request.
   * @type {string}
   */
  request: string;
  /**
   * The content generated by the agent.
   * @type {string}
   */
  content: string;
  /**
   * Critique and recommendations for the generated content.
   * @type {string}
   */
  critique: string;
  /**
   * Messages exchanged during the workflow.
   * @type {BaseMessage[]}
   */
  messages: BaseMessage[];
  /**
   * The next node to execute in the workflow.
   * @type {string}
   */
  next: string;
};
