
import { BaseMessage } from "@langchain/core/messages";

/**
 * Represents the state for a Rewoo workflow.
 * @interface
 */
export type RewooState = {
  /**
   * The user's initial task for the Rewoo workflow.
   * @type {string}
   */
  task: string;
  /**
   * The plan generated by the Planner, as a string.
   * @type {string}
   */
  planString: string;
  /**
   * A list of steps in the plan, where each step is an array of strings.
   * @type {string[][]}
   */
  steps: string[][];
  /**
   * Results from tool executions, stored as a record where keys are step IDs and values are tool outputs.
   * @type {Record<string, any>}
   */
  results: Record<string, any>;
  /**
   * The final result generated by the Solver.
   * @type {string}
   */
  result: string;
  /**
   * Messages exchanged during the Rewoo process.
   * @type {BaseMessage[]}
   */
  messages: BaseMessage[];
  /**
   * The next node to execute in the workflow.
   * @type {string}
   */
  next: string;
};
